### ISSUE TITLE
Improve error handling for project addition, allow parenthesis in description   

### ISSUE THREAD

**Issue by RemeJuan** [melezhik/mybfio#3]
Adding a project via the website results in a generic error message “Incorrect input data”

Data being submitted:
Project name: Lattr
Project url: https://github.com/RemeJuan/lattr
Project description: Lattr (later) is a small API driven Twitter scheduler, in practice, it would be something like a lite version of Buffer or Hootsuite.
Language: golang 
Category: applications

May also be nice if the form data did not clear after failed submission.

**Comment by melezhik** [comment]
the problem was due to parenthesis were not allowed in a project description, now they are, please try again

> May also be nice if the form data did not clear after failed submission.

I partly fixed that as well, but need to take care about options lists

**Comment by melezhik** [comment]
> Adding a project via the website results in a generic error message “Incorrect input data”

now in case of incorrect input more specific messages are shown

**Comment by melezhik** [comment]
@RemeJuan you can try to add your project now, please let me know if it works , thanks

**Comment by RemeJuan** [comment]
All sorted @melezhik

**Comment by melezhik** [comment]
@RemeJuan cool. do you want to add your project to the #mybfio contest ?

**Comment by RemeJuan** [comment]
@melezhik I submitted it already, or did I miss a step?

**Comment by melezhik** [comment]
you added your project to the web site, now when I have your consent I will add it to the contest list. no worries )))

**Comment by melezhik** [comment]
done!
